version: '3'
services:
  app:
    build: .
    volumes:
      - ${HF_HOME:-~/.cache/huggingface/hub}:/app/.cache/huggingface/hub
      - ./scratch:/app/scratch/
      - ./models:/app/models/
    environment:
      - HF_HOME=/app/.cache/huggingface/hub
    command: python3 app.py
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]